// src/services/xmlEngine.js
// EN 16931 / XRechnung 3.0 / ZUGFeRD 2.4 XML Generator + Validator
// Mustang-compatible output

import { createHash } from 'crypto';

// ── HELPERS ───────────────────────────────────────────────────
const esc = (str) => String(str || '')
  .replace(/&/g, '&amp;').replace(/</g, '&lt;')
  .replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;');

const fmt = (n) => parseFloat(n || 0).toFixed(2);

// ── EN 16931 VALIDATION ───────────────────────────────────────
export function validateEN16931(invoice) {
  const errors = [];
  const warnings = [];

  // BT-1: Invoice number
  if (!invoice.invoice_number) errors.push({ code: 'BT-1', msg: 'Rechnungsnummer fehlt (BT-1)' });

  // BT-2: Invoice date
  if (!invoice.invoice_date) errors.push({ code: 'BT-2', msg: 'Rechnungsdatum fehlt (BT-2)' });

  // BT-11: Seller name
  if (!invoice.seller_name) errors.push({ code: 'BT-27', msg: 'Name des Verkäufers fehlt (BT-27)' });

  // BT-44: Buyer name
  if (!invoice.buyer_name) errors.push({ code: 'BT-44', msg: 'Name des Käufers fehlt (BT-44)' });

  // BT-31: Seller VAT ID
  if (!invoice.seller_vat_id) warnings.push({ code: 'BT-31', msg: 'USt-IdNr. des Verkäufers empfohlen (BT-31)' });

  // BT-112: Invoice total
  if (!invoice.amount_gross || invoice.amount_gross <= 0)
    errors.push({ code: 'BT-112', msg: 'Rechnungsbetrag ungültig (BT-112)' });

  // BR-CO-10: VAT breakdown required
  if (!invoice.line_items || invoice.line_items.length === 0)
    errors.push({ code: 'BR-16', msg: 'Mindestens eine Rechnungsposition erforderlich (BR-16)' });

  // Line item validation
  (invoice.line_items || []).forEach((item, i) => {
    if (!item.description) errors.push({ code: `BT-153-L${i+1}`, msg: `Position ${i+1}: Beschreibung fehlt` });
    if (!item.quantity || item.quantity <= 0) errors.push({ code: `BT-129-L${i+1}`, msg: `Position ${i+1}: Menge ungültig` });
    if (item.unit_price === undefined) errors.push({ code: `BT-146-L${i+1}`, msg: `Position ${i+1}: Einzelpreis fehlt` });
    if (item.vat_rate === undefined) warnings.push({ code: `BT-152-L${i+1}`, msg: `Position ${i+1}: MwSt-Satz nicht angegeben` });
  });

  // BT-9: Due date recommended
  if (!invoice.due_date) warnings.push({ code: 'BT-9', msg: 'Fälligkeitsdatum empfohlen (BT-9)' });

  const passed = errors.length === 0;
  return { passed, errors, warnings, standard: 'EN 16931', version: '1.3.4' };
}

// ── XRECHNUNG GENERATOR (UBL 2.1) ─────────────────────────────
export function generateXRechnung(invoice) {
  const net = (invoice.line_items || []).reduce((s, i) => s + (i.quantity * i.unit_price), 0);
  const vatAmt = (invoice.line_items || []).reduce((s, i) => s + (i.quantity * i.unit_price * ((i.vat_rate || 19) / 100)), 0);
  const gross = net + vatAmt;

  // Group VAT by rate
  const vatGroups = {};
  (invoice.line_items || []).forEach(item => {
    const rate = item.vat_rate || 19;
    if (!vatGroups[rate]) vatGroups[rate] = { taxableAmount: 0, taxAmount: 0 };
    vatGroups[rate].taxableAmount += item.quantity * item.unit_price;
    vatGroups[rate].taxAmount += item.quantity * item.unit_price * (rate / 100);
  });

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<ubl:Invoice
  xmlns:ubl="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2"
  xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2"
  xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2">

  <!-- Generated by invoiq — https://invoiq.io -->
  <!-- Standard: XRechnung 3.0 / EN 16931 / UBL 2.1 -->

  <cbc:CustomizationID>urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_3.0</cbc:CustomizationID>
  <cbc:ProfileID>urn:fdc:peppol.eu:2017:poacc:billing:01:1.0</cbc:ProfileID>
  <cbc:ID>${esc(invoice.invoice_number)}</cbc:ID>
  <cbc:IssueDate>${invoice.invoice_date}</cbc:IssueDate>
  ${invoice.due_date ? `<cbc:DueDate>${invoice.due_date}</cbc:DueDate>` : ''}
  <cbc:InvoiceTypeCode>380</cbc:InvoiceTypeCode>
  <cbc:DocumentCurrencyCode>${invoice.currency || 'EUR'}</cbc:DocumentCurrencyCode>
  <cbc:BuyerReference>${esc(invoice.reference || invoice.buyer_name)}</cbc:BuyerReference>

  <!-- Seller (BT-27 ff.) -->
  <cac:AccountingSupplierParty>
    <cac:Party>
      <cac:PartyName>
        <cbc:Name>${esc(invoice.seller_name)}</cbc:Name>
      </cac:PartyName>
      <cac:PostalAddress>
        <cbc:StreetName>${esc(invoice.seller_address || '')}</cbc:StreetName>
        <cbc:CityName>${esc(invoice.seller_city || '')}</cbc:CityName>
        <cac:Country><cbc:IdentificationCode>${invoice.seller_country || 'DE'}</cbc:IdentificationCode></cac:Country>
      </cac:PostalAddress>
      <cac:PartyTaxScheme>
        <cbc:CompanyID>${esc(invoice.seller_vat_id || '')}</cbc:CompanyID>
        <cac:TaxScheme><cbc:ID>VAT</cbc:ID></cac:TaxScheme>
      </cac:PartyTaxScheme>
      <cac:PartyLegalEntity>
        <cbc:RegistrationName>${esc(invoice.seller_name)}</cbc:RegistrationName>
      </cac:PartyLegalEntity>
      ${invoice.seller_iban ? `
      <cac:FinancialAccount>
        <cbc:ID>${esc(invoice.seller_iban)}</cbc:ID>
      </cac:FinancialAccount>` : ''}
    </cac:Party>
  </cac:AccountingSupplierParty>

  <!-- Buyer (BT-44 ff.) -->
  <cac:AccountingCustomerParty>
    <cac:Party>
      <cac:PartyName>
        <cbc:Name>${esc(invoice.buyer_name)}</cbc:Name>
      </cac:PartyName>
      <cac:PostalAddress>
        <cbc:StreetName>${esc(invoice.buyer_address || '')}</cbc:StreetName>
        <cbc:CityName>${esc(invoice.buyer_city || '')}</cbc:CityName>
        <cac:Country><cbc:IdentificationCode>${invoice.buyer_country || 'DE'}</cbc:IdentificationCode></cac:Country>
      </cac:PostalAddress>
      ${invoice.buyer_vat_id ? `
      <cac:PartyTaxScheme>
        <cbc:CompanyID>${esc(invoice.buyer_vat_id)}</cbc:CompanyID>
        <cac:TaxScheme><cbc:ID>VAT</cbc:ID></cac:TaxScheme>
      </cac:PartyTaxScheme>` : ''}
      <cac:PartyLegalEntity>
        <cbc:RegistrationName>${esc(invoice.buyer_name)}</cbc:RegistrationName>
      </cac:PartyLegalEntity>
    </cac:Party>
  </cac:AccountingCustomerParty>

  <!-- VAT Breakdown (BG-23) -->
  <cac:TaxTotal>
    <cbc:TaxAmount currencyID="${invoice.currency || 'EUR'}">${fmt(vatAmt)}</cbc:TaxAmount>
    ${Object.entries(vatGroups).map(([rate, g]) => `
    <cac:TaxSubtotal>
      <cbc:TaxableAmount currencyID="${invoice.currency || 'EUR'}">${fmt(g.taxableAmount)}</cbc:TaxableAmount>
      <cbc:TaxAmount currencyID="${invoice.currency || 'EUR'}">${fmt(g.taxAmount)}</cbc:TaxAmount>
      <cac:TaxCategory>
        <cbc:ID>S</cbc:ID>
        <cbc:Percent>${rate}</cbc:Percent>
        <cac:TaxScheme><cbc:ID>VAT</cbc:ID></cac:TaxScheme>
      </cac:TaxCategory>
    </cac:TaxSubtotal>`).join('')}
  </cac:TaxTotal>

  <!-- Totals (BG-22) -->
  <cac:LegalMonetaryTotal>
    <cbc:LineExtensionAmount currencyID="${invoice.currency || 'EUR'}">${fmt(net)}</cbc:LineExtensionAmount>
    <cbc:TaxExclusiveAmount currencyID="${invoice.currency || 'EUR'}">${fmt(net)}</cbc:TaxExclusiveAmount>
    <cbc:TaxInclusiveAmount currencyID="${invoice.currency || 'EUR'}">${fmt(gross)}</cbc:TaxInclusiveAmount>
    <cbc:PayableAmount currencyID="${invoice.currency || 'EUR'}">${fmt(gross)}</cbc:PayableAmount>
  </cac:LegalMonetaryTotal>

  <!-- Line Items (BG-25) -->
  ${(invoice.line_items || []).map((item, idx) => `
  <cac:InvoiceLine>
    <cbc:ID>${idx + 1}</cbc:ID>
    <cbc:InvoicedQuantity unitCode="${item.unit || 'C62'}">${item.quantity}</cbc:InvoicedQuantity>
    <cbc:LineExtensionAmount currencyID="${invoice.currency || 'EUR'}">${fmt(item.quantity * item.unit_price)}</cbc:LineExtensionAmount>
    <cac:Item>
      <cbc:Description>${esc(item.description)}</cbc:Description>
      <cbc:Name>${esc(item.description)}</cbc:Name>
      <cac:ClassifiedTaxCategory>
        <cbc:ID>S</cbc:ID>
        <cbc:Percent>${item.vat_rate || 19}</cbc:Percent>
        <cac:TaxScheme><cbc:ID>VAT</cbc:ID></cac:TaxScheme>
      </cac:ClassifiedTaxCategory>
    </cac:Item>
    <cac:Price>
      <cbc:PriceAmount currencyID="${invoice.currency || 'EUR'}">${fmt(item.unit_price)}</cbc:PriceAmount>
    </cac:Price>
  </cac:InvoiceLine>`).join('')}

</ubl:Invoice>`;

  return xml.trim();
}

// ── ZUGFERD 2.4 GENERATOR (CII / Cross Industry Invoice) ─────
export function generateZUGFeRD(invoice) {
  const net = (invoice.line_items || []).reduce((s, i) => s + (i.quantity * i.unit_price), 0);
  const vatAmt = (invoice.line_items || []).reduce((s, i) => s + (i.quantity * i.unit_price * ((i.vat_rate || 19) / 100)), 0);
  const gross = net + vatAmt;

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<rsm:CrossIndustryInvoice
  xmlns:rsm="urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100"
  xmlns:qdt="urn:un:unece:uncefact:data:standard:QualifiedDataType:100"
  xmlns:ram="urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:udt="urn:un:unece:uncefact:data:standard:UnqualifiedDataType:100">

  <!-- Generated by invoiq — ZUGFeRD 2.4 / EN 16931 -->

  <rsm:ExchangedDocumentContext>
    <ram:GuidelineSpecifiedDocumentContextParameter>
      <ram:ID>urn:cen.eu:en16931:2017#conformant#urn:factur-x.eu:1p0:extended</ram:ID>
    </ram:GuidelineSpecifiedDocumentContextParameter>
  </rsm:ExchangedDocumentContext>

  <rsm:ExchangedDocument>
    <ram:ID>${esc(invoice.invoice_number)}</ram:ID>
    <ram:TypeCode>380</ram:TypeCode>
    <ram:IssueDateTime>
      <udt:DateTimeString format="102">${(invoice.invoice_date || '').replace(/-/g, '')}</udt:DateTimeString>
    </ram:IssueDateTime>
  </rsm:ExchangedDocument>

  <rsm:SupplyChainTradeTransaction>
    <!-- Line Items -->
    ${(invoice.line_items || []).map((item, idx) => `
    <ram:IncludedSupplyChainTradeLineItem>
      <ram:AssociatedDocumentLineDocument>
        <ram:LineID>${idx + 1}</ram:LineID>
      </ram:AssociatedDocumentLineDocument>
      <ram:SpecifiedTradeProduct>
        <ram:Name>${esc(item.description)}</ram:Name>
      </ram:SpecifiedTradeProduct>
      <ram:SpecifiedLineTradeAgreement>
        <ram:NetPriceProductTradePrice>
          <ram:ChargeAmount>${fmt(item.unit_price)}</ram:ChargeAmount>
        </ram:NetPriceProductTradePrice>
      </ram:SpecifiedLineTradeAgreement>
      <ram:SpecifiedLineTradeDelivery>
        <ram:BilledQuantity unitCode="${item.unit || 'C62'}">${item.quantity}</ram:BilledQuantity>
      </ram:SpecifiedLineTradeDelivery>
      <ram:SpecifiedLineTradeSettlement>
        <ram:ApplicableTradeTax>
          <ram:TypeCode>VAT</ram:TypeCode>
          <ram:CategoryCode>S</ram:CategoryCode>
          <ram:RateApplicablePercent>${item.vat_rate || 19}</ram:RateApplicablePercent>
        </ram:ApplicableTradeTax>
        <ram:SpecifiedTradeSettlementLineMonetarySummation>
          <ram:LineTotalAmount>${fmt(item.quantity * item.unit_price)}</ram:LineTotalAmount>
        </ram:SpecifiedTradeSettlementLineMonetarySummation>
      </ram:SpecifiedLineTradeSettlement>
    </ram:IncludedSupplyChainTradeLineItem>`).join('')}

    <!-- Header -->
    <ram:ApplicableHeaderTradeAgreement>
      <ram:SellerTradeParty>
        <ram:Name>${esc(invoice.seller_name)}</ram:Name>
        <ram:PostalTradeAddress>
          <ram:LineOne>${esc(invoice.seller_address || '')}</ram:LineOne>
          <ram:CityName>${esc(invoice.seller_city || '')}</ram:CityName>
          <ram:CountryID>${invoice.seller_country || 'DE'}</ram:CountryID>
        </ram:PostalTradeAddress>
        ${invoice.seller_vat_id ? `
        <ram:SpecifiedTaxRegistration>
          <ram:ID schemeID="VA">${esc(invoice.seller_vat_id)}</ram:ID>
        </ram:SpecifiedTaxRegistration>` : ''}
      </ram:SellerTradeParty>
      <ram:BuyerTradeParty>
        <ram:Name>${esc(invoice.buyer_name)}</ram:Name>
        <ram:PostalTradeAddress>
          <ram:LineOne>${esc(invoice.buyer_address || '')}</ram:LineOne>
          <ram:CityName>${esc(invoice.buyer_city || '')}</ram:CityName>
          <ram:CountryID>${invoice.buyer_country || 'DE'}</ram:CountryID>
        </ram:PostalTradeAddress>
      </ram:BuyerTradeParty>
    </ram:ApplicableHeaderTradeAgreement>

    <ram:ApplicableHeaderTradeDelivery/>

    <ram:ApplicableHeaderTradeSettlement>
      <ram:InvoiceCurrencyCode>${invoice.currency || 'EUR'}</ram:InvoiceCurrencyCode>
      <ram:ApplicableTradeTax>
        <ram:CalculatedAmount>${fmt(vatAmt)}</ram:CalculatedAmount>
        <ram:TypeCode>VAT</ram:TypeCode>
        <ram:BasisAmount>${fmt(net)}</ram:BasisAmount>
        <ram:CategoryCode>S</ram:CategoryCode>
        <ram:RateApplicablePercent>19</ram:RateApplicablePercent>
      </ram:ApplicableTradeTax>
      ${invoice.due_date ? `
      <ram:SpecifiedTradePaymentTerms>
        <ram:DueDateDateTime>
          <udt:DateTimeString format="102">${(invoice.due_date || '').replace(/-/g, '')}</udt:DateTimeString>
        </ram:DueDateDateTime>
      </ram:SpecifiedTradePaymentTerms>` : ''}
      <ram:SpecifiedTradeSettlementHeaderMonetarySummation>
        <ram:LineTotalAmount>${fmt(net)}</ram:LineTotalAmount>
        <ram:TaxBasisTotalAmount>${fmt(net)}</ram:TaxBasisTotalAmount>
        <ram:TaxTotalAmount currencyID="${invoice.currency || 'EUR'}">${fmt(vatAmt)}</ram:TaxTotalAmount>
        <ram:GrandTotalAmount>${fmt(gross)}</ram:GrandTotalAmount>
        <ram:DuePayableAmount>${fmt(gross)}</ram:DuePayableAmount>
      </ram:SpecifiedTradeSettlementHeaderMonetarySummation>
    </ram:ApplicableHeaderTradeSettlement>
  </rsm:SupplyChainTradeTransaction>

</rsm:CrossIndustryInvoice>`;

  return xml.trim();
}

// ── DISPATCH ─────────────────────────────────────────────────

export function generateFacturX(invoice) {
  // FacturX 1.0 — technisch identisch zu ZUGFeRD 2.x, anderes Profil-ID
  // Profil EN_16931 = "Comfort" (vollständige Rechnung)
  const base = generateZUGFeRD(invoice);
  return base
    .replace(
      'urn:cen.eu:en16931:2017#conformant#urn:factur-x.eu:1p0:extended',
      'urn:cen.eu:en16931:2017#compliant#urn:factur-x.eu:1p0:en16931'
    )
    .replace(
      '<!-- Generated by invoiq — ZUGFeRD 2.4 / EN 16931 -->',
      '<!-- Generated by invoiq — FacturX 1.0 EN_16931 / EN 16931 -->'
    );
}


export function generateXML(invoice) {
  switch (invoice.format) {
    case 'zugferd':
    case 'facturx':   return generateFacturX(invoice);
    case 'xrechnung':
    case 'peppol':
    default:          return generateXRechnung(invoice);
  }
}

// ── HASH (GoBD integrity) ─────────────────────────────────────
export function hashXML(xml) {
  return createHash('sha256').update(xml, 'utf8').digest('hex');
}

// ── PARSE INBOUND XML ─────────────────────────────────────────
export function parseInboundXML(xmlString) {
  try {
    // Detect format
    const isZUGFeRD = xmlString.includes('CrossIndustryInvoice');
    const isUBL = xmlString.includes('ubl:Invoice');

    if (!isZUGFeRD && !isUBL) {
      return { success: false, error: 'Unbekanntes XML-Format' };
    }

    // Basic extraction (production: use full XML parser)
    const extract = (pattern) => {
      const m = xmlString.match(pattern);
      return m ? m[1].trim() : null;
    };

    if (isUBL) {
      return {
        success: true,
        format: 'xrechnung',
        data: {
          invoice_number: extract(/<cbc:ID>([^<]+)<\/cbc:ID>/),
          invoice_date: extract(/<cbc:IssueDate>([^<]+)<\/cbc:IssueDate>/),
          due_date: extract(/<cbc:DueDate>([^<]+)<\/cbc:DueDate>/),
          seller_name: extract(/<cac:AccountingSupplierParty>[\s\S]*?<cbc:Name>([^<]+)<\/cbc:Name>/),
          buyer_name: extract(/<cac:AccountingCustomerParty>[\s\S]*?<cbc:Name>([^<]+)<\/cbc:Name>/),
          amount_gross: parseFloat(extract(/<cbc:PayableAmount[^>]*>([^<]+)<\/cbc:PayableAmount>/) || '0'),
        }
      };
    }

    if (isZUGFeRD) {
      return {
        success: true,
        format: 'zugferd',
        data: {
          invoice_number: extract(/<ram:ID>([^<]+)<\/ram:ID>/),
          invoice_date: extract(/<udt:DateTimeString format="102">([^<]+)<\/udt:DateTimeString>/),
          seller_name: extract(/<ram:SellerTradeParty>[\s\S]*?<ram:Name>([^<]+)<\/ram:Name>/),
          buyer_name: extract(/<ram:BuyerTradeParty>[\s\S]*?<ram:Name>([^<]+)<\/ram:Name>/),
          amount_gross: parseFloat(extract(/<ram:GrandTotalAmount>([^<]+)<\/ram:GrandTotalAmount>/) || '0'),
        }
      };
    }
  } catch (err) {
    return { success: false, error: err.message };
  }
}
